# Generated by Django 3.2.7 on 2021-10-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20211002_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': 'Area'},
        ),
        migrations.AlterModelOptions(
            name='central_authority',
            options={'verbose_name_plural': 'Central_Authority'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payment'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='service_provider',
            options={'verbose_name_plural': 'Service_Providers'},
        ),
        migrations.AlterModelOptions(
            name='service_type',
            options={'verbose_name_plural': 'Service_type'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='authority_paid',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_paid',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='problem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(),
        ),
    ]
