# Generated by Django 3.2.7 on 2021-10-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20211003_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Central_Authority',
        ),
    ]
