# Generated by Django 3.2.7 on 2021-10-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_delete_central_authority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='service',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_provider_id',
        ),
        migrations.RemoveField(
            model_name='service_provider',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='service_provider',
            name='service_id',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Service_Provider',
        ),
        migrations.DeleteModel(
            name='Service_type',
        ),
    ]
