# Generated by Django 3.2.7 on 2021-10-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20211006_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=8)),
                ('service_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Service_type',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=8)),
                ('customer_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=8)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_area', to='database.area')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Admin_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=8)),
                ('admin_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=11)),
                ('login_as', models.CharField(choices=[('CENTRAL_AUTHORITY', 'Central_Authority'), ('MANAGER', 'Manager'), ('SERVICE_PROVIDER', 'Service_Provider')], default='Service_Provider', max_length=19)),
                ('nid', models.CharField(blank=True, max_length=17)),
                ('password', models.CharField(max_length=8)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='database.area')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Provided_Service', to='database.service_type')),
            ],
            options={
                'verbose_name_plural': 'Admin_table',
            },
        ),
    ]
