# Generated by Django 3.2.7 on 2021-10-05 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_admin_table_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_table',
            name='area_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='database.area'),
        ),
        migrations.AlterField(
            model_name='admin_table',
            name='nid',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='admin_table',
            name='service_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Provided_Service', to='database.service_type'),
        ),
    ]
