# Generated by Django 3.2.7 on 2021-10-05 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20211006_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_table',
            name='area_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_area', to='database.area'),
        ),
    ]
