# Generated by Django 3.2.7 on 2021-10-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20211006_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin_table',
            options={'verbose_name_plural': 'Admins'},
        ),
    ]
