# Generated by Django 3.2.7 on 2021-10-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_admin_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin_table',
            options={'verbose_name_plural': 'Admin_table'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='authority_paid',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_paid',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(),
        ),
    ]
