# Generated by Django 3.2.7 on 2021-10-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20211007_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
