# Generated by Django 3.2.7 on 2021-10-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_service_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_table',
            new_name='Admin',
        ),
    ]
