# Generated by Django 3.2.7 on 2021-10-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_rename_admin_table_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admins'},
        ),
    ]
