# Generated by Django 3.2.7 on 2021-10-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_id',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='receipt_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='service_type',
            name='service_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
