# Generated by Django 3.0.8 on 2021-10-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20211022_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='login_as',
            field=models.CharField(choices=[('CENTRAL AUTHORITY', 'Central Authority'), ('MANAGER', 'Manager'), ('SERVICE PROVIDER', 'Service Provider')], default='Service_Provider', max_length=19),
        ),
    ]
