# Generated by Django 3.0.8 on 2021-10-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20211025_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Status',
            field=models.CharField(blank=True, choices=[('Due', 'Due'), ('Processing', 'Processing'), ('Complete', 'Complete')], default='Due', max_length=15, null=True),
        ),
    ]
