# Generated by Django 3.0.8 on 2021-10-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8, unique=True)),
                ('provider_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=11)),
                ('nid', models.CharField(blank=True, max_length=17)),
                ('active', models.CharField(choices=[('D', 'D'), ('C', 'C')], default='Y', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='receipt_number',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service_type',
            options={},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='area',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_provider_id',
        ),
        migrations.RemoveField(
            model_name='service_type',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='service_type',
            name='service_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='review',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service_type',
            name='service_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='authority_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Status',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('C', 'C')], default='Due', max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='area',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_area', to='database.Area'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Provided_Service', to='database.Service_type'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='database.ServiceProvider'),
        ),
    ]
