# Generated by Django 3.0.8 on 2021-10-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20211030_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='service_type',
            name='service_category',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='active',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=2),
        ),
    ]
