# Generated by Django 3.0.8 on 2021-10-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20211030_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Status',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('C', 'C')], default='D', max_length=15, null=True),
        ),
    ]
