# Generated by Django 3.0.8 on 2021-10-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20211030_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
