# Generated by Django 3.0.8 on 2021-10-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_remove_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='username',
        ),
    ]
