# Generated by Django 3.0.8 on 2021-11-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_remove_serviceprovider_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area_name',
            new_name='name',
        ),
    ]
