# Generated by Django 3.2.8 on 2021-11-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_auto_20211105_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='database.customer'),
        ),
    ]
