# Generated by Django 3.0.8 on 2021-11-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_auto_20211106_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='temp',
        ),
    ]
